name: FastAPI CI/CD with Pyenv, Pipenv, and Docker
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev

    - name: Run Tests
      run: pipenv run pytest

    - name: Build Docker image
      run: docker build -t fastapi-app .

    # Add steps for Docker push and deploy to Azure if needed
   
